version: '3'
services:
  mongo:
    image: mongo:6
    container_name: chatapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CLIENT_ORIGIN=http://localhost:3000 
      - MONGO_URI=mongodb+srv://Harshavardhan:CanvasHarsha123@cluster0.pwqr9zz.mongodb.net/chatapp

    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SOCKET_SERVER_URL=http://localhost:5000
    # REMOVE volumes for production, or it will overwrite /app/.next

volumes:
  mongo_data:
